config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :challenges
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  get "sendit" => "todos#sendit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge.rb
class Challenge < ApplicationRecord
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  skip_before_action :verify_authenticity_token
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: %i[ show edit update destroy ]

  # GET /challenges or /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1 or /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges or /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: "Challenge was successfully created." }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1 or /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: "Challenge was successfully updated." }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1 or /challenges/1.json
  def destroy
    @challenge.destroy!

    respond_to do |format|
      format.html { redirect_to challenges_path, status: :see_other, notice: "Challenge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def challenge_params
      params.expect(challenge: [ :title, :description ])
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  def sendit
    ActionCable.server.broadcast("todo_channel", { todos: Todo.all.to_json })
    render json: { status: "ok" }
  end

  # GET /todos or /todos.json
  def index
    @todos = Todo.all.order(:completed, :order)
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        ActionCable.server.broadcast("todo_channel", { todos: Todo.all.to_json })
        format.html { redirect_to @todo, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        ActionCable.server.broadcast("todo_channel", { todos: Todo.all.to_json })
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      ActionCable.server.broadcast("todo_channel", { todos: Todo.all.to_json })
      format.html { redirect_to todos_path, status: :see_other, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.expect(todo: [ :title, :order, :completed ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/challenges/_challenge.html.erb
<div id="<%= dom_id challenge %>">
  <p>
    <strong>Title:</strong>
    <%= challenge.title %>
  </p>

  <%= tag.div(data: { controller: "markdown", markdown_input_value: challenge.description }) do %>
    <%= tag.div(data: { markdown_target: "output" }) %>
  <% end %>
</div>

app/views/challenges/_form.html.erb
<%= form_with(model: challenge) do |form| %>
  <% if challenge.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
        <% challenge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <%= tag.div(style: "display: flex;", data: { controller: "markdown" }) do %>
    <div style="flex: 1; padding-right: 10px;">
      <%= form.label :description, style: "display: block" %>
      <%= form.textarea :description, data: { markdown_target: "input" }, rows: 30 %>
    </div>

    <div style="flex: 1; padding-left: 10px;">
      <%= form.label :preview, "Preview", style: "display: block" %>
      <%= tag.div(class: "preview", data: { markdown_target: "output" }) %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<% content_for :title, "Editing challenge" %>

<h1>Editing challenge</h1>

<%= render "form", challenge: @challenge %>

<br>

<div>
  <%= link_to "Show this challenge", @challenge %> |
  <%= link_to "Back to challenges", challenges_path %>
</div>

app/views/challenges/index.html.erb
<p style="color: green" data-controller="notice" data-notice-duration-value="2000"><%= notice %></p>

<% content_for :title, "Challenges" %>

<h1>Challenges</h1>

<div id="challenges">
  <% @challenges.each do |challenge| %>
    <%= render challenge %>
    <p>
      <%= link_to "Show this challenge", challenge %>
    </p>
  <% end %>
</div>

<%= link_to "New challenge", new_challenge_path %>

app/views/challenges/new.html.erb
<% content_for :title, "New challenge" %>

<h1>New challenge</h1>

<%= render "form", challenge: @challenge %>

<br>

<div>
  <%= link_to "Back to challenges", challenges_path %>
</div>

app/views/challenges/show.html.erb
<p style="color: green" data-controller="notice" data-notice-duration-value="2000"><%= notice %></p>

<%= render @challenge %>

<div>
  <%= link_to "Edit this challenge", edit_challenge_path(@challenge) %> |
  <%= link_to "Back to challenges", challenges_path %>

  <%= button_to "Destroy this challenge", @challenge, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Kinetic" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :order, style: "display: block" %>
    <%= form.number_field :order %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Title:</strong>
    <%= todo.title %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= todo.order %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= todo.completed %>
  </p>
</div>

app/views/todos/edit.html.erb
<% content_for :title, "Editing todo" %>

<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Todos" %>

<h1>Todos</h1>

<div id="todos">

</div>

<%= link_to "New todo", new_todo_path %>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    fetch("/sendit")
  });
</script>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>

<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>